package com.harbdm.urbanexplorer.presentation.ui.screens.add_edit_spot

import android.util.Log
import androidx.compose.runtime.State
import androidx.compose.runtime.mutableStateOf
import androidx.compose.ui.res.stringResource
import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.harbdm.urbanexplorer.domain.model.InvalidSpotException
import com.harbdm.urbanexplorer.domain.model.Photo
import com.harbdm.urbanexplorer.domain.model.Spot
import com.harbdm.urbanexplorer.domain.usecase.FileUseCases
import com.harbdm.urbanexplorer.domain.usecase.SpotUseCases
import com.harbdm.urbanexplorer.presentation.model.SpotTypeUiProvider
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import okio.IOException
import javax.inject.Inject

@HiltViewModel
class AddEditSpotViewModel @Inject constructor(
    private val spotUseCases: SpotUseCases,
    private val fileUseCases: FileUseCases,
    savedStateHandle: SavedStateHandle
) : ViewModel() {
    private val _spotState = MutableStateFlow(AddEditSpotState())
    val spotState: StateFlow<AddEditSpotState> = _spotState.asStateFlow()

    private val _eventFlow = MutableSharedFlow<UiEvent>()
    val eventFlow = _eventFlow.asSharedFlow()

    /**
     * Should load spot with Hilt provided spotId after navigation as soon as VM init,
     * or change loading status if new spot to immediately update TopBar status
     */
    init {
        savedStateHandle.get<Long>("spotId")?.let { spotId ->
            if (spotId.toInt() != -1) {
                viewModelScope.launch {
                    spotUseCases.getSpotById(spotId)?.also { spot ->
                        _spotState.update {
                            it.copy(
                                it.spotTitle.copy(
                                    text = spot.spotName
                                ),
                                it.spotDescription.copy(
                                    text = spot.spotDescription ?: ""
                                ),
                                it.spotLocationHint.copy(
                                    text = spot.locationHint
                                ),
                                spotType = SpotTypeUiProvider.fromString(spot.spotType),
                                spotRating = spot.spotRating,
                                spotId = spot.id,
                                spotPhotos = spot.photos,
                                spotLoading = false
                            )
                        }
                    }
                }
            } else {
                _spotState.update {
                    it.copy(
                        spotLoading = false
                    )
                }
            }
        }
    }

    fun onEvent(event: AddEditSpotEvent) {
        when (event) {
            is AddEditSpotEvent.OnTittleChanged -> {
                _spotState.update {
                    it.copy(
                        spotTitle = it.spotTitle.copy(
                            text = event.tittle
                        )
                    )
                }
            }

            is AddEditSpotEvent.OnTypeChanged -> {
                _spotState.update {
                    it.copy(
                        spotType = event.type
                    )
                }
            }

            is AddEditSpotEvent.OnDescriptionChanged -> {
                _spotState.update {
                    it.copy(
                        spotDescription = it.spotDescription.copy(
                            text = event.description
                        )
                    )
                }
            }

            is AddEditSpotEvent.OnLocationHintChanged -> {
                _spotState.update {
                    it.copy(
                        spotLocationHint = it.spotLocationHint.copy(
                            text = event.locationHint
                        )
                    )
                }
            }

            is AddEditSpotEvent.OnPhotoAdded -> {
                viewModelScope.launch {
                    try {
                        fileUseCases.savePhotoUseCase(event.photoUri).let { newUri->
                            _spotState.update {
                                it.copy(
                                    spotPhotos = it.spotPhotos + Photo(
                                        photoId = 0,
                                        // Should set id of spot owner to 0 in case new spot
                                        // to db provide new autogenerated id
                                        spotOwnerId = if (spotState.value.spotId.toInt() != -1) spotState.value.spotId
                                        else 0,
                                        uriString = newUri.data.toString(),
                                        caption = ""
                                    )
                                )
                            }
                        }
                    }catch (e: Exception){
                        _eventFlow.emit(UiEvent.ShowSnackbar(e.message?: "Can't save photo"))
                    }
                }
            }

            is AddEditSpotEvent.OnPhotoDeleted -> {
                _spotState.update {
                    it.copy(
                        spotPhotos = it.spotPhotos - event.photo
                    )
                }
            }

            is AddEditSpotEvent.OnRatingChanged -> {
                _spotState.update {
                    it.copy(
                        spotRating = event.rating
                    )
                }
            }

            AddEditSpotEvent.OnSaveSpotClicked -> {
                viewModelScope.launch {
                    try {
                        spotUseCases.addSpotWithPhotos(
                            Spot(
                                spotName = spotState.value.spotTitle.text,
                                spotType = spotState.value.spotType.key,
                                spotDescription = spotState.value.spotDescription.text,
                                locationHint = spotState.value.spotLocationHint.text,
                                spotRating = spotState.value.spotRating,
                                timeStamp = System.currentTimeMillis(),
                                photos = spotState.value.spotPhotos,
                                // can't directly pass id -1 if new spot, should set to 0
                                // to autogenerate new id
                                id = if (spotState.value.spotId.toInt() != -1) spotState.value.spotId else 0
                            )
                        )
                        _eventFlow.emit(
                            UiEvent.SaveSpotSuccess
                        )
                    } catch (e: InvalidSpotException) {
                        _eventFlow.emit(
                            UiEvent.ShowSnackbar(
                                message = e.message ?: "Can't save the spot :("
                            )
                        )
                    }
                }
            }

            is AddEditSpotEvent.OnCameraClicked -> {
                viewModelScope.launch {
                    _eventFlow.emit(UiEvent.LaunchCamera)
                }
            }

            is AddEditSpotEvent.OnGalleryClicked -> {
                viewModelScope.launch {
                    _eventFlow.emit(UiEvent.LaunchGallery)
                }
            }
        }
    }


    sealed class UiEvent {
        data class ShowSnackbar(val message: String) : UiEvent()
        object LaunchGallery : UiEvent()
        object LaunchCamera : UiEvent()
        object SaveSpotSuccess : UiEvent()
    }
}